package squidr

// example config
// var _allowPost contains a generated list of all currently allowed git repo targets
var _allowPost = map[string]bool{
	"api-iam.intercom.io":          true,
	"sso.arbeitsagentur.de":        true,
	"www.arbeitsagentur.de":        true,
	"con.arbeitsagentur.de":        true,
	"web.arbeitsagentur.de":        true,
	"web.intern.arbeitsagentur.de": true,
	"rest.arbeitsagentur.de":       true,
	"account-api.proton.me":        true,
	"account.proton.me":            true,
	"mail.proton.me":               true,
	"news.ycombinator.com":         true,
	"infosec.exchange":             true,
	"bugs.freebsd.org":             true,
	"reviews.freebsd.org":          true,
	"www.hvv.de":                   true,
	"shop.hvv.de":                  true,
	"www.lbv-termine.de":           true,
	"www.dell.com":                 true,
	"api.funcaptcha.com":           true,
	"api.hcaptcha.com":             true,
	"accounts.bahn.de":             true,
	"fahrkarten.bahn.de":           true,
	"duckduckgo.com":               true,
	"lite.duckduckgo.com":          true,
	"html.duckduckgo.com":          true,
	"challenges.cloudflare.com":    true,
	"api.openai.com":               true,
	"store.google.com":             true,
	"beta.openai.com":              true,
	"auth0.openai.com":             true,
	"labs.openai.com":              true,
	"platform.openai.com":          true,
	"chat.openai.com":              true,
	"accounts.google.com":          true,
	"mail.google.com":              true,
	"pkg.go.dev":                   true,
	"www.reichelt.de":              true,
	"www.berrybase.de":             true,
	"meta.sr.ht":                   true,
	"gitlab-api.arkoselabs.com":    true,
	"www.recaptcha.net":            true,
	"tineye.com":                   true,
	"compresspng.com":              true,
	"tinypng.com":                  true,
	"uploads.github.com":           true,
}
